config/routes.rb
Rails.application.routes.draw do
  resources :course_groups

  resources :courses

  resources :test_system_users

  resources :duties

  resources :disciplines

  resources :students

  resources :student_group_memberships

  resources :student_groups

  resources :teachers

    root 'welcome#index'
  get 'welcome/index'

  devise_for :users

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :discipline
  belongs_to :teacher
  
  has_many :course_groups
  has_many :groups, through: :course_groups
  
  accepts_nested_attributes_for :course_groups
end

app/models/course_group.rb
class CourseGroup < ActiveRecord::Base
  belongs_to :course
  belongs_to :group, class_name: "StudentGroup", foreign_key: "group_id"
  
  def to_label
    
    "lol"
  end
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  
  
 def to_label
   "#{name}"
 end
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :Discipline
  belongs_to :Teacher
end

app/models/student.rb
class Student < TestSystemUser
  has_one :student_group_membership
  belongs_to :student_group 
   default_scope {where(accesslevel: 4)}
 

  def to_label
    "#{firstname} #{middlename} #{lastname}"
  end
  
  validates_presence_of :student_group_membership
  
  accepts_nested_attributes_for :student_group_membership
 
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  has_many :student_group_membership
  has_many :student, through: :student_group_membership
  
  has_many :course_groups, foreign_key: "group_id"
  has_many :courses, through: :course_groups  
  
  
  def to_label
    "#{groupname}"
  end
end

app/models/teacher.rb
class Teacher < TestSystemUser
 #Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)
 default_scope {where(accesslevel: 2)}
 
  
  def to_label
    "#{firstname} #{middlename} #{lastname}"
  end
end

app/models/test_system_user.rb
class TestSystemUser < User
    scope :teachers, -> {where(accesslevel: 2)}
    scope :students, -> {where(accesslevel: 2)} 
    
    validates :firstname, length: {minimum: 1}
    validates :lastname, length: {minimum: 1}   
    validates :login, length: {in: 5..12}
    validates :accesslevel, 
      numericality: {only_integer: true}, 
      presence: true, inclusion: {in: [1, 2, 4]}
    validates :login, uniqueness: true;      
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    @all_groups = StudentGroup.all
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.includes(:course_groups).find(params[:id])
      @all_groups = StudentGroup.all
      
    end

    def course_params
      params.require(:course).permit(:discipline_id, :teacher_id, :coursename, :group_ids => []
      )
    end
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_action :set_duty, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @duties = Duty.all
    respond_with(@duties)
  end

  def show
    respond_with(@duty)
  end

  def new
    @duty = Duty.new
    respond_with(@duty)
  end

  def edit
  end

  def create
    @duty = Duty.new(duty_params)
    @duty.save
    respond_with(@duty)
  end

  def update
    @duty.update(duty_params)
    respond_with(@duty)
  end

  def destroy
    @duty.destroy
    respond_with(@duty)
  end

  private
    def set_duty
      @duty = Duty.find(params[:id])
    end

    def duty_params
      params.require(:duty).permit(:Discipline_id, :Teacher_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :get_groups, only: [:edit, :new]

  respond_to :html
  def index
    @students = Student.all
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    @student.build_student_group_membership
    respond_with(@student)
  end

  def edit
  end

  def create
    logger.info(student_params.to_s);
    @student = Student.new(student_params)
    @student.password = @student.email + '12345678'
    @student.accesslevel = 4
    @student.save
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private

  def set_student
    @student = Student.includes(:student_group_membership).find(params[:id])
  end

  def get_groups
    @studentgroups = StudentGroup.all
  end

  def student_params
  #  params[:student][:student_group_memberships][0] = params[:student][:student_group_membership]
    params.require(:student).permit(:login, :firstname, :middlename, :lastname, :email, 
    {student_group_membership_attributes: [:student_group_id]})
  end

 


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @teachers = Teacher.all
    respond_with(@teachers)
  end

  def show
    respond_with(@teacher)
  end

  def new
    @teacher = Teacher.new
    respond_with(@teacher)
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.password = @teacher.email + '12345678'
    @teacher.accesslevel = 2
    @teacher.save
    respond_with(@teacher)
  end

  def update
    @teacher.update(teacher_params)
    respond_with(@teacher)
  end

  def destroy
    @teacher.destroy
    respond_with(@teacher)
  end

  private
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:login, :firstname, :middlename, :lastname, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_groups_helper.rb
module CourseGroupsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/helpers/student_groups_helper.rb
module StudentGroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/duties/_form.html.haml
= simple_form_for(@duty) do |f|
  = f.error_notification

  .form-inputs
    = f.association :Discipline
    = f.association :Teacher

  .form-actions
    = f.button :submit

app/views/duties/edit.html.haml
%h1 Editing duty

= render 'form'

= link_to 'Show', @duty
\|
= link_to 'Back', duties_path

app/views/duties/index.html.haml
%h1 Listing duties

%table
  %thead
    %tr
      %th Discipline
      %th Teacher
      %th
      %th
      %th
      
  %tbody
    - @duties.each do |duty|
      %tr
        %td= duty.Discipline
        %td= duty.Teacher
        %td= link_to 'Show', duty
        %td= link_to 'Edit', edit_duty_path(duty)
        %td= link_to 'Destroy', duty, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Duty', new_duty_path

app/views/duties/new.html.haml
%h1 New duty

= render 'form'

= link_to 'Back', duties_path

app/views/duties/show.html.haml
%p#notice= notice

%p
  %b Discipline:
  = @duty.Discipline
%p
  %b Teacher:
  = @duty.Teacher

= link_to 'Edit', edit_duty_path(@duty)
\|
= link_to 'Back', duties_path

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  = f.error_notification

  .form-inputs
    = f.input :login
    = f.input :firstname
    = f.input :middlename
    = f.input :lastname
    = f.input :email
    = f.simple_fields_for :student_group_membership, @student.student_group_membership do |m|
      = m.association :student_group

  .form-actions
    = f.button :submit

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Login
      %th Firstname
      %th Middlename
      %th Lastname
      %th Email
      %th
      %th
      %th
      
  %tbody
    - @students.each do |student|
      %tr
        %td= student.login
        %td= student.firstname
        %td= student.middlename
        %td= student.lastname
        %td= student.email
        %td= link_to 'Show', student
        %td= link_to 'Edit', edit_student_path(student)
        %td= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Login:
  = @student.login
%p
  %b Firstname:
  = @student.firstname
%p
  %b Middlename:
  = @student.middlename
%p
  %b Lastname:
  = @student.lastname
%p
  %b Email:
  = @student.email

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path

app/views/teachers/_form.html.haml
= simple_form_for(@teacher) do |f|
  = f.error_notification

  .form-inputs
    = f.input :login
    = f.input :firstname
    = f.input :middlename
    = f.input :lastname
    = f.input :email

  .form-actions
    = f.button :submit

app/views/teachers/edit.html.haml
%h1 Editing teacher

= render 'form'

= link_to 'Show', @teacher
\|
= link_to 'Back', teachers_path

app/views/teachers/index.html.haml
%h1 Listing teachers

%table
  %thead
    %tr
      %th Login
      %th Firstname
      %th Middlename
      %th Lastname
      %th Email
      %th
      %th
      %th
      
  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= teacher.login
        %td= teacher.firstname
        %td= teacher.middlename
        %td= teacher.lastname
        %td= teacher.email
        %td= link_to 'Show', teacher
        %td= link_to 'Edit', edit_teacher_path(teacher)
        %td= link_to 'Destroy', teacher, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Teacher', new_teacher_path

app/views/teachers/new.html.haml
%h1 New teacher

= render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
%p#notice= notice

%p
  %b Login:
  = @teacher.login
%p
  %b Firstname:
  = @teacher.firstname
%p
  %b Middlename:
  = @teacher.middlename
%p
  %b Lastname:
  = @teacher.lastname
%p
  %b Email:
  = @teacher.email

= link_to 'Edit', edit_teacher_path(@teacher)
\|
= link_to 'Back', teachers_path