config/routes.rb
Rails.application.routes.draw do
  resources :course_groups

  resources :courses

  resources :test_system_users

  resources :duties

  resources :disciplines

  resources :students

  resources :student_group_memberships

  resources :student_groups

  resources :teachers

    root 'welcome#index'
  get 'welcome/index'

  devise_for :users

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :discipline
  belongs_to :teacher
  
  has_many :course_groups
  has_many :groups, through: :course_groups
  
  accepts_nested_attributes_for :course_groups
end

app/models/course_group.rb
class CourseGroup < ActiveRecord::Base
  belongs_to :course
  belongs_to :group, class_name: "StudentGroup", foreign_key: "group_id"
  
  def to_label
    
    "lol"
  end
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  
  
 def to_label
   "#{name}"
 end
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :Discipline
  belongs_to :Teacher
end

app/models/student.rb
class Student < TestSystemUser
  has_one :student_group_membership
  belongs_to :student_group 
   default_scope {where(accesslevel: 4)}
 

  def to_label
    "#{firstname} #{middlename} #{lastname}"
  end
  
  validates_presence_of :student_group_membership
  
  accepts_nested_attributes_for :student_group_membership
 
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  has_many :student_group_membership
  has_many :student, through: :student_group_membership
  
  has_many :course_groups, foreign_key: "group_id"
  has_many :courses, through: :course_groups  
  
  
  def to_label
    "#{groupname}"
  end
end

app/models/teacher.rb
class Teacher < TestSystemUser
 #Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)
 default_scope {where(accesslevel: 2)}
 
  
  def to_label
    "#{firstname} #{middlename} #{lastname}"
  end
end

app/models/test_system_user.rb
class TestSystemUser < User
    scope :teachers, -> {where(accesslevel: 2)}
    scope :students, -> {where(accesslevel: 2)} 
    
    validates :firstname, length: {minimum: 1}
    validates :lastname, length: {minimum: 1}   
    validates :login, length: {in: 5..12}
    validates :accesslevel, 
      numericality: {only_integer: true}, 
      presence: true, inclusion: {in: [1, 2, 4]}
    validates :login, uniqueness: true;      
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    @all_groups = StudentGroup.all
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.includes(:course_groups).find(params[:id])
      @all_groups = StudentGroup.all
      
    end

    def course_params
      params.require(:course).permit(:discipline_id, :teacher_id, :coursename, :group_ids => []
      )
    end
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_action :set_duty, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @duties = Duty.all
    respond_with(@duties)
  end

  def show
    respond_with(@duty)
  end

  def new
    @duty = Duty.new
    respond_with(@duty)
  end

  def edit
  end

  def create
    @duty = Duty.new(duty_params)
    @duty.save
    respond_with(@duty)
  end

  def update
    @duty.update(duty_params)
    respond_with(@duty)
  end

  def destroy
    @duty.destroy
    respond_with(@duty)
  end

  private
    def set_duty
      @duty = Duty.find(params[:id])
    end

    def duty_params
      params.require(:duty).permit(:Discipline_id, :Teacher_id)
    end
end

app/controllers/test_system_users_controller.rb
class TestSystemUsersController < ApplicationController
  before_action :set_test_system_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @test_system_users = TestSystemUser.all
    respond_with(@test_system_users)
  end

  def show
    respond_with(@test_system_user)
  end

  def new
    @test_system_user = TestSystemUser.new
    respond_with(@test_system_user)
  end

  def edit
  end

  def create
    @test_system_user = TestSystemUser.new(test_system_user_params)
    @test_system_user.save
    respond_with(@test_system_user)
  end

  def update
    @test_system_user.update(test_system_user_params)
    respond_with(@test_system_user)
  end

  def destroy
    @test_system_user.destroy
    respond_with(@test_system_user)
  end

  private
    def set_test_system_user
      @test_system_user = TestSystemUser.find(params[:id])
    end

    def test_system_user_params
      params.require(:test_system_user).permit(:login, :firstname, :middlename, :lastname)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_groups_helper.rb
module CourseGroupsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/helpers/student_groups_helper.rb
module StudentGroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/test_system_users_helper.rb
module TestSystemUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/test_system_users/_form.html.haml
= simple_form_for(@test_system_user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :login
    = f.input :firstname
    = f.input :middlename
    = f.input :lastname

  .form-actions
    = f.button :submit

app/views/test_system_users/edit.html.haml
%h1 Editing test_system_user

= render 'form'

= link_to 'Show', @test_system_user
\|
= link_to 'Back', test_system_users_path

app/views/test_system_users/index.html.haml
%h1 Listing test_system_users

%table
  %thead
    %tr
      %th Login
      %th Firstname
      %th Middlename
      %th Lastname
      %th
      %th
      %th
      
  %tbody
    - @test_system_users.each do |test_system_user|
      %tr
        %td= test_system_user.login
        %td= test_system_user.firstname
        %td= test_system_user.middlename
        %td= test_system_user.lastname
        %td= link_to 'Show', test_system_user
        %td= link_to 'Edit', edit_test_system_user_path(test_system_user)
        %td= link_to 'Destroy', test_system_user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Test system user', new_test_system_user_path

app/views/test_system_users/new.html.haml
%h1 New test_system_user

= render 'form'

= link_to 'Back', test_system_users_path

app/views/test_system_users/show.html.haml
%p#notice= notice

%p
  %b Login:
  = @test_system_user.login
%p
  %b Firstname:
  = @test_system_user.firstname
%p
  %b Middlename:
  = @test_system_user.middlename
%p
  %b Lastname:
  = @test_system_user.lastname

= link_to 'Edit', edit_test_system_user_path(@test_system_user)
\|
= link_to 'Back', test_system_users_path